baseURL: https://aryaman73.github.io #TODO: should this be aryamans.me?
languageCode: en-us
title: aryamans.me
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hey! \U0001F44B"
    Content: >
      - I'm Aryaman, a software developer based in Waterloo! 🇨🇦 I recently graduated from the University of Waterloo's Computer Engineering program. 🎓

      - 

      - In the past, I've worked at Tesla as a Software Engineering Intern in the Firmware Build & Infra team, where I worked on large-scale infrastructure projects using Typescript, Python and Ruby. I've also worked at Relay Platform, Versett, Telus and PointClickCare, where I built and maintained large scale applications with React, Ruby on Rails, Java and more. I enjoy building accessible, reliable and thoughtfully-designed applications that focus on the end-user above all.
      
      - 

      - You might have met me volunteering with Midnight Sun, Waterloo ECE Society, Waterloo Engineering Competition or HackTheNorth.
      
      - 

      - Feel free to reach out to me if you want to talk, work together or just vent about CSS. 

  socialIcons:
    - name: GitHub
      url: "https://github.com/aryaman73"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/aryamans/"
    - name: Dev
      url: "https://devpost.com/Aryaman73"
    - name: Email
      url: "mailto:a553sing@uwaterloo.ca"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: "20"
    - identifier: resume
      name: resume
      url: /resume.pdf
      weight: "20"
