baseURL: https://aryaman73.github.io #TODO: should this be aryamans.me?
languageCode: en-us
title: aryamans.me
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hey! \U0001F44B"
    Content: >
      - I'm Aryaman, a 3B Computer Engineering Student at the University of Waterloo.

      - 

      - I've worked at companies like Relay Platform, Versett, Telus and PointClickCare, where I built and maintained large scale applications with React, Ruby on Rails, Java and more. I enjoy building accessible, reliable and thoughtfully-designed applications that focus on the end-user above all.
      
      - 

      - I'm currently part of the Waterloo Engineering Society, working as a the Website Director and WEC Technical Director. In the past, you might have met me volunteering with Midnight Sun, Waterloo ECE Society, or HackTheNorth. 
      
      - 

      - Feel free to reach out to me if you want to talk, work together or just vent about CSS. Oh, and I'm also looking for 2023 Summer/Fall internship opportunities 👀.

  socialIcons:
    - name: GitHub
      url: "https://github.com/aryaman73"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/aryamans/"
    - name: Email
      url: "mailto:a553sing@uwaterloo.ca"
    # TODO: figure out Devpost Icon
    - name: Devpost
      url: "https://devpost.com/Aryaman73"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: "20"
    - identifier: resume
      name: resume
      url: /resume.pdf
      weight: "20"
