baseURL: https://aryaman73.github.io
languageCode: en-us
title: aryamans.me
theme: PaperMod

# TODO: should baseUrl this be aryamans.me?

params:
  homeInfoParams:
    Title: "Hey! \U0001F44B"
    Content: >
      - I'm Aryaman, a software developer based in Toronto! 🇨🇦 I recently graduated from the University of Waterloo's Computer Engineering program. 🎓

      - 

      - Previously, I interned at Tesla as a Software Engineer on the Firmware Build & Infrastructure team, where I contributed to large-scale infrastructure projects using TypeScript, Python, and Ruby. I’ve also worked at Telus, PointClickCare, and Versett, creating accessible, reliable, and thoughtfully-designed applications with a focus on user experience.
      
      - 

      - Outside of work, you might know me as a mentor at HackTheNorth and StarterHacks or from volunteering with Midnight Sun, the Waterloo ECE Society, and the Waterloo Engineering Competition.
      
      - 

      - Feel free to reach out if you'd like to connect, collaborate, or just chat about all things software 🫠

  socialIcons:
    - name: GitHub
      url: "https://github.com/aryaman73"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/aryamans/"
    - name: Dev
      url: "https://devpost.com/Aryaman73"
    - name: Email
      url: "mailto:a553sing@uwaterloo.ca"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: "20"
    - identifier: resume
      name: resume
      url: /resume.pdf
      weight: "20"
